- hosts: localhost

- tasks:
  - name: create http, http and SSH
    amazon.aws.ec2_group:
      name: "{{ digital_house021 }}"
      vpc_id: vpc-0fcea564
      description: sg with the rules
      region: us-west-1
      rules:
        - proto: tcp
          ports:
            - 443
            - 80
            - 22
          cidr_ip: 0.0.0.0/0
          rule_desc: Accept all the traffic in the ports 443, 80 e 22
          
  - name: We created our server
    ec2:
      region: us-west-1
      instance_type: t2.micro
      image: ami-0ed05376b59b90e46
      wait: yes
      wait_timeout: 500
      volumes:
        - device_name: / dev / xvda
        - volume_type: gp2
        - volume_size: 8
      vpc_subnet_id: subnet-070d3b818d23ea3cf
      assign_public_ip: yes
      key_name: digitalhouse
    register: info
    
  - name: server public IP
    debug:
      var: info.instances [0] .public_ip
  - name: server public DNS
    debug:
      var: info.instances [0] .public_dns_name