---
- hosts: localhost
- tasks:
- name: Criar grupo de segurança com HTTPS, HTTP e SSH
  ec2_group:
    name: digitalhouse021
    vpc_id: vpc-0fcea564
    description: sg com as regras
    region: us-west-1
    rules:
      - proto: tcp
        ports:
        - 443
        - 80
        - 22
        cidr_ip: 0.0.0.0/0
        rule_desc: Aceito todo o tráfego nas portas 443, 80 e 22
- name: Nós criamos nosso servidor
  ec2:
    region: us-west-1
    instance_type: t2.micro
    image: ami-0ed05376b59b90e46
    wait: sim
    wait_timeout: 500
    volumes:
      - device_name: / dev / xvda
      - volume_type: gp2
      - volume_size: 8
    vpc_subnet_id: subnet-070d3b818d23ea3cf
    assign_public_ip: sim
    key_name: digitalhouse021
  register: info
- name: IP público do nosso servidor
  debug:
    var: info.instances [0] .public_ip
- name: DNS público de nosso servidor
  debug:
    var: info.instances [0] .public_dns_name